### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by kokuyouwind** [kishaningithub/setup-tf-summarize#68]
When I used this Action, I received the following warning.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: kishaningithub/setup-tf-summarize@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Please update the following line to use Node.js 20: https://github.com/kishaningithub/setup-tf-summarize/blob/main/action.yml#L14 .

**Comment by kishaningithub** [comment]
@kokuyouwind Have now published the [v2](https://github.com/kishaningithub/setup-tf-summarize/releases/tag/v2.0.0) version with your changes. Thanks for your contribution! :-)
